### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'read' in nbformat 

### ISSUE THREAD

**Issue by narendraprasath** [dexplo/jupyter_to_medium#19]
Getting the following error when I try to publish a notebook to the medium article.

Anaconda 3.6.5 on Windows
jupyter-to-medium==0.2.4

What could be the root cause for this problem?
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_to_medium\_bundler.py", line 37, in upload
    data = publish(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_to_medium\_publish_to_medium.py", line 299, in publish
    chrome_path, save_markdown, table_conversion)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_to_medium\_publish_to_medium.py", line 41, in __init__
    self.nb = self.get_notebook()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_to_medium\_publish_to_medium.py", line 76, in get_notebook
    return nbformat.read(self.filename, as_version=4)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
AttributeError: 'WindowsPath' object has no attribute 'read'
```

**Comment by narendraprasath** [comment]
Got fixed. Previously I was using `nbformat==4.4`. Now, I updated to the latest version to `nbformat==5.0.7`

**Comment by adallak** [comment]
I have the same problem, even after updating nbformat package

**Comment by lukmanulhakeem97** [comment]
> Got fixed. Previously I was using `nbformat==4.4`. Now, I updated to the latest version to `nbformat==5.0.7`

facing same issue, tried this one still have issue. Please help..
