### ISSUE TITLE
Problems with PosixPath

### ISSUE THREAD

**Issue by saidsalihefendic** [dexplo/jupyter_to_medium#20]
Hi there,

Thank you for providing us with this automation.

I am using Ubuntu 18.04 Operating System and I have created a Jupyter Notebook that I want to publish on Medium.

Following your instructions, I have encountered on a problem:

Traceback (most recent call last):
  File "publish_to_jupyter.py", line 13, in <module>
    table_conversion='chrome'
  File "/home/saidsalihefendic/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py", line 299, in publish
    chrome_path, save_markdown, table_conversion)
  File "/home/saidsalihefendic/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py", line 41, in __init__
    self.nb = self.get_notebook()
  File "/home/saidsalihefendic/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py", line 76, in get_notebook
    return nbformat.read(self.filename, as_version=4)
  File "/home/saidsalihefendic/miniconda3/lib/python3.7/site-packages/nbformat/__init__.py", line 140, in read
    return reads(fp.read(), as_version, **kwargs)
AttributeError: 'PosixPath' object has no attribute 'read'

I have tried to insert a valid and invalid name of Jupyter notebook, but I get the same error.

Any ideas how I can resolve this issue?

Thank you in advance!

**Comment by jingxinfu** [comment]
Hi, I meet the same problem, and update the `nbformat` solved my problem.
here is the cmd:
```
pip install --upgrade nbformat
```

**Comment by mjam03** [comment]
Is this still a problem you are experiencing? If so please let me know and I'll re-open the issue and check if pinning nbformat as a dependency will fi the issue.

If it persists pls can you post some environment details so I can attempt to replicate as I locally run MacOS and not Ubuntu
