### ISSUE TITLE
BUG: conversion of DataFrame to image using Matplotlib fails with list index out of range

### ISSUE THREAD

**Issue by discdiver** [dexplo/jupyter_to_medium#6]
I have a single column pandas DataFrame. That uploads to Medium using jtm just fine.

 Then I use sidetable to make a DataFrame with a Grand Total row. Now uploading fails.

 This was just an example to test jtm. 

Package versions:
jupyter_to_medium 0.1.0
pandas 1.0.5
sidetable 0.5.0

jtm.publish( table_conversion="matplotlib")

Reproducible code:
```
import pandas as pd
import sidetable as stb
df=pd.DataFrame(dict(a=[1,3, 5]))
df.stb.subtotal()
```

Error stack trace:
```
Traceback (most recent call last):
  File "jtm_script.py", line 15, in <module>
    table_conversion="matplotlib",
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py", line 311, in publish
    p.main()
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py", line 230, in main
    self.md, self.image_data_dict = self.create_markdown()
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_publish_to_medium.py", line 128, in create_markdown
    self.nb, self.resources = no_ex_pp.preprocess(self.nb, self.resources)
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_preprocesors.py", line 124, in preprocess_cell
    output['data'] = {'image/png': converter(html)}
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_matplotlib_table.py", line 140, in mpl_make_table
    rowColours = [c[0] for c in cellColours]
  File "/Users/jeffhale/miniconda3/lib/python3.7/site-packages/jupyter_to_medium/_matplotlib_table.py", line 140, in <listcomp>
    rowColours = [c[0] for c in cellColours]
IndexError: list index out of range
```

**Comment by tdpetrou** [comment]
I was unable to reproduce this error and successfully posted to Medium with the matplotlib table. Can you try again after upgrading to 0.1.1?

**Comment by discdiver** [comment]
fixed with upgrade. closing. Thank you.

**Comment by tdpetrou** [comment]
@discdiver Thanks again for creating these issues! Would have taken much longer to find these bugs without them.
